import { PriceMatrixItem } from "./types";

export const initialPriceMatrixData: PriceMatrixItem[] = [
  {
    id: "sut-001",
    name: "ข้าวกล่อง (สำหรับผู้เข้าร่วมกิจกรรม/สตาฟ)",
    itemName: "ข้าวกล่อง (สำหรับผู้เข้าร่วมกิจกรรม/สตาฟ)",
    category: "หมวดโภชนาการ",
    price: 50,
    maxPrice: 50,
    unit: "บาท/มื้อ",
    unitPrice: 50,
    unitType: "บาท/มื้อ",
    pricingType: "per_person",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 24 * 2,
  },
  {
    id: "sut-002",
    name: "อาหารว่างและเครื่องดื่ม (Snack Box)",
    itemName: "อาหารว่างและเครื่องดื่ม (Snack Box)",
    category: "หมวดโภชนาการ",
    price: 35,
    maxPrice: 35,
    unit: "บาท/ชุด",
    unitPrice: 35,
    unitType: "บาท/ชุด",
    pricingType: "per_person",
    maxCap: null,
    exclusiveWith: ["น้ำแดงเฮลบลูบอย"],
    updatedAt: Date.now() - 3600000 * 24 * 1,
  },
  {
    id: "sut-003",
    name: "น้ำดื่มบรรจุขวด SUT (600 ml)",
    itemName: "น้ำดื่มบรรจุขวด SUT (600 ml)",
    category: "หมวดโภชนาการ",
    price: 60,
    maxPrice: 60,
    unit: "บาท/แพ็ค",
    unitPrice: 60,
    unitType: "บาท/แพ็ค",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 12,
  },
  {
    id: "sut-004",
    name: "ป้ายไวนิลประชาสัมพันธ์โครงการ (พร้อมเจาะตาไก่)",
    itemName: "ป้ายไวนิลประชาสัมพันธ์โครงการ (พร้อมเจาะตาไก่)",
    category: "หมวดอุปกรณ์สำนักงาน",
    price: 150,
    maxPrice: 150,
    unit: "บาท/ตร.ม.",
    unitPrice: 150,
    unitType: "บาท/ตร.ม.",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 48,
  },
  {
    id: "sut-005",
    name: "เข็มกอปรปัญญา/ของที่ระลึกวิทยากร",
    itemName: "เข็มกอปรปัญญา/ของที่ระลึกวิทยากร",
    category: "หมวดอุปกรณ์สำนักงาน",
    price: 350,
    maxPrice: 350,
    unit: "บาท/ชิ้น",
    unitPrice: 350,
    unitType: "บาท/ชิ้น",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: ["ค่าวิทยากร (ภายนอก)", "ค่าวิทยากร (ภายใน)"],
    updatedAt: Date.now() - 3600000 * 36,
  },
  {
    id: "sut-006",
    name: "เกียรติบัตรพิมพ์สีพร้อมปกวุฒิบัตร",
    itemName: "เกียรติบัตรพิมพ์สีพร้อมปกวุฒิบัตร",
    category: "หมวดอุปกรณ์สำนักงาน",
    price: 25,
    maxPrice: 25,
    unit: "บาท/ใบ",
    unitPrice: 25,
    unitType: "บาท/ใบ",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 5,
  },
  {
    id: "sut-007",
    name: "ค่าตอบแทนวิทยากรภายนอก (ระดับเชี่ยวชาญ)",
    itemName: "ค่าตอบแทนวิทยากรภายนอก (ระดับเชี่ยวชาญ)",
    category: "หมวดค่าตอบแทน",
    price: 1200,
    maxPrice: 1200,
    unit: "บาท/ชม.",
    unitPrice: 1200,
    unitType: "บาท/ชม.",
    pricingType: "per_person",
    maxCap: 2400,
    exclusiveWith: ["ค่าของที่ระลึก"],
    updatedAt: Date.now() - 3600000 * 10,
  },
  {
    id: "sut-008",
    name: "ค่าบริการเช่าเครื่องเสียงและไฟเวทีกลางแจ้ง",
    itemName: "ค่าบริการเช่าเครื่องเสียงและไฟเวทีกลางแจ้ง",
    category: "หมวดอุปกรณ์อิเล็กทรอนิกส์",
    price: 5000,
    maxPrice: 5000,
    unit: "บาท/วัน",
    unitPrice: 5000,
    unitType: "บาท/วัน",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 3,
  },
  {
    id: "sut-009",
    name: "ค่าบริการรถบัสรับ-ส่งกิจกรรมนอกสถานที่",
    itemName: "ค่าบริการรถบัสรับ-ส่งกิจกรรมนอกสถานที่",
    category: "หมวดพาหนะ",
    price: 4500,
    maxPrice: 4500,
    unit: "บาท/คัน/วัน",
    unitPrice: 4500,
    unitType: "บาท/คัน/วัน",
    pricingType: "unit",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 8,
  },
  {
    id: "sut-010",
    name: "อุปกรณ์การจัดฐานกิจกรรมและสันทนาการ",
    itemName: "อุปกรณ์การจัดฐานกิจกรรมและสันทนาการ",
    category: "หมวดอุปกรณ์ก่อสร้าง",
    price: 2000,
    maxPrice: 2000,
    unit: "บาท/ชุดโครงการ",
    unitPrice: 2000,
    unitType: "บาท/ชุดโครงการ",
    pricingType: "project_fixed",
    maxCap: null,
    exclusiveWith: [],
    updatedAt: Date.now() - 3600000 * 2,
  },
  {
    id: "sut-011",
    name: "ค่าจ้างพนักงานไฟฟ้าและซ่อมบำรุง (วันจันทร์-ศุกร์ เวลาราชการ)",
    itemName: "ค่าจ้างพนักงานไฟฟ้าและซ่อมบำรุง (วันจันทร์-ศุกร์ เวลาราชการ)",
    category: "หมวดค่าตอบแทน",
    price: 240,
    maxPrice: 240,
    unit: "คน/วัน",
    unitPrice: 240,
    unitType: "คน/วัน",
    pricingType: "per_person",
    maxCap: null,
    exclusiveWith: [],
    condition: "WEEKDAY",
    note: "วันจันทร์-วันศุกร์ ในเวลาราชการ",
    updatedAt: Date.now() - 3600000 * 4,
  },
  {
    id: "sut-012",
    name: "ค่าจ้างพนักงานไฟฟ้าและซ่อมบำรุง (วันเสาร์-อาทิตย์ และวันหยุดนักขัตฤกษ์)",
    itemName: "ค่าจ้างพนักงานไฟฟ้าและซ่อมบำรุง (วันเสาร์-อาทิตย์ และวันหยุดนักขัตฤกษ์)",
    category: "หมวดค่าตอบแทน",
    price: 420,
    maxPrice: 420,
    unit: "คน/วัน",
    unitPrice: 420,
    unitType: "คน/วัน",
    pricingType: "per_person",
    maxCap: null,
    exclusiveWith: [],
    condition: "WEEKEND",
    note: "วันเสาร์-อาทิตย์ และวันหยุดนักขัตฤกษ์",
    updatedAt: Date.now() - 3600000 * 4,
  },
];
