import { PriceMatrixItem } from "./types";

export const initialPriceMatrixData: PriceMatrixItem[] = [
  {
    id: "sut-001",
    itemName: "ข้าวกล่อง (สำหรับผู้เข้าร่วมกิจกรรม/สตาฟ)",
    category: "อาหาร",
    maxPrice: 50,
    unit: "บาท/มื้อ",
    unitPrice: 50,
    unitType: "บาท/มื้อ",
    updatedAt: Date.now() - 3600000 * 24 * 2,
  },
  {
    id: "sut-002",
    itemName: "อาหารว่างและเครื่องดื่ม (Snack Box)",
    category: "อาหาร",
    maxPrice: 35,
    unit: "บาท/ชุด",
    unitPrice: 35,
    unitType: "บาท/ชุด",
    updatedAt: Date.now() - 3600000 * 24 * 1,
  },
  {
    id: "sut-003",
    itemName: "น้ำดื่มบรรจุขวด SUT (600 ml)",
    category: "อาหาร",
    maxPrice: 60,
    unit: "บาท/แพ็ค",
    unitPrice: 60,
    unitType: "บาท/แพ็ค",
    updatedAt: Date.now() - 3600000 * 12,
  },
  {
    id: "sut-004",
    itemName: "ป้ายไวนิลประชาสัมพันธ์โครงการ (พร้อมเจาะตาไก่)",
    category: "อุปกรณ์สำนักงาน",
    maxPrice: 150,
    unit: "บาท/ตร.ม.",
    unitPrice: 150,
    unitType: "บาท/ตร.ม.",
    updatedAt: Date.now() - 3600000 * 48,
  },
  {
    id: "sut-005",
    itemName: "เข็มกอปรปัญญา/ของที่ระลึกวิทยากร",
    category: "อุปกรณ์สำนักงาน",
    maxPrice: 350,
    unit: "บาท/ชิ้น",
    unitPrice: 350,
    unitType: "บาท/ชิ้น",
    updatedAt: Date.now() - 3600000 * 36,
  },
  {
    id: "sut-006",
    itemName: "เกียรติบัตรพิมพ์สีพร้อมปกวุฒิบัตร",
    category: "อุปกรณ์สำนักงาน",
    maxPrice: 25,
    unit: "บาท/ใบ",
    unitPrice: 25,
    unitType: "บาท/ใบ",
    updatedAt: Date.now() - 3600000 * 5,
  },
  {
    id: "sut-007",
    itemName: "ค่าตอบแทนวิทยากรภายนอก (ระดับเชี่ยวชาญ)",
    category: "บริการ",
    maxPrice: 1200,
    unit: "บาท/ชม.",
    unitPrice: 1200,
    unitType: "บาท/ชม.",
    updatedAt: Date.now() - 3600000 * 10,
  },
  {
    id: "sut-008",
    itemName: "ค่าบริการเช่าเครื่องเสียงและไฟเวทีกลางแจ้ง",
    category: "บริการ",
    maxPrice: 5000,
    unit: "บาท/วัน",
    unitPrice: 5000,
    unitType: "บาท/วัน",
    updatedAt: Date.now() - 3600000 * 3,
  },
  {
    id: "sut-009",
    itemName: "ค่าบริการรถบัสรับ-ส่งกิจกรรมนอกสถานที่",
    category: "บริการ",
    maxPrice: 4500,
    unit: "บาท/คัน/วัน",
    unitPrice: 4500,
    unitType: "บาท/คัน/วัน",
    updatedAt: Date.now() - 3600000 * 8,
  },
  {
    id: "sut-010",
    itemName: "อุปกรณ์การจัดฐานกิจกรรมและสันทนาการ",
    category: "อื่นๆ",
    maxPrice: 2000,
    unit: "บาท/ชุดโครงการ",
    unitPrice: 2000,
    unitType: "บาท/ชุดโครงการ",
    updatedAt: Date.now() - 3600000 * 2,
  },
];
